# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16efS0umq1u-OC4sQUKfOOd6bDA_vJ8zP

ASSIGNMENT
"""

import numpy as np

A =np.array([[[18,14,73,46],[24,7,95,27]],[[17,20,80,22],[43,14,23,36]]])
print(A)

x=np.where(A==14)
print(x)

print(np.sort(A))